### ISSUE TITLE
Get words definition

### ISSUE THREAD

**Issue by Nipher** [gabrielgodoy/getme#16]
Something like
```
$ getme definition consent
$ getme def consent
```

And then show something like this:
![screen shot 2017-01-04 at 1 11 26 am](https://cloud.githubusercontent.com/assets/7523828/21630711/e704af12-d21a-11e6-9238-d5b422248a0c.png)

Maybe we can use some API like this one: https://www.wordsapi.com/
I'll try to contribute with a PR during this week :)

**Comment by willianjusten** [comment]
This one is really good and important to me!!

**Comment by Nipher** [comment]
@willianjusten ikr? I would use it A LOT

And btw, I didn't mention this on the issue (maybe we can create a new issue for each language), but after adding it in English, we could see how to integrate with APIs in other languages, like German for example

Something like:
```
$ getme def --language=german Grenzen
```
and get
![screen shot 2017-01-04 at 2 03 45 pm](https://cloud.githubusercontent.com/assets/7523828/21648944/091aa28e-d287-11e6-9430-e0cb7292fd46.png)

**Comment by gabrielgodoy** [comment]
Shipped the definition of words option on latest release 1.2.7

`getme definition teacher` Definition of *teacher*
`getme d teacher` Shorthand for definitions
`getme definition -s teacher` Get synonyms

**Comment by Nipher** [comment]
Awesome!  🎉   
let's close this then, if we come up with any new ideas for improvement or APIs for other languages we open new issues for that!
