### ISSUE TITLE
Github notifications

### ISSUE THREAD

**Issue by psicotropicos** [gabrielgodoy/getme#47]
I was thinking about a command to read the Github notifications.

Somenthing like:
```
$ getme notifications // Show all unread notifications
```

What do you think?

**Comment by gabrielgodoy** [comment]
Sounds good to me. 

To get user notifications from the Github API like that:

`getme notifications` 

I think we would need to authenticate the user. And the user would need to generate an access token and so on.


There are other projects that display notifications too, and maybe we can get some ideas from them:

[gh](https://github.com/node-gh/gh)
To show notification from a repo for example: `gh notification --user expressjs --repo express`

[Notifier chrome extension](https://github.com/sindresorhus/notifier-for-github-chrome)

**Comment by psicotropicos** [comment]
Do you think it's interesting to get notifications from repositories?
I was thinking in get only personal notifications

**Comment by gabrielgodoy** [comment]
Yes, I was just showing that to get notifications from repositories you don't need authorization from the user.

But to get personal notifications,  [authorization from the user is required](https://developer.github.com/v3/activity/notifications/). 

####There are some ways we can get authorization to display user notification:
* [Basic authentication](https://developer.github.com/v3/auth/#basic-authentication), with Username and Password
For basic auth, we would need to request username and password:

`curl -u [USER]:[PASSWORD]  https://api.github.com/notifications`

* [OAuth](https://developer.github.com/v3/oauth/)
We would need to ask for user authorization, and then after user authorization, we would need to store the access token in some place to query for notifications with that token.

**Comment by robbiegleeson** [comment]
@gabrielgodoy  If nobody wants to take this you can assign it to me.

You can use basic auth in a request to get notifications for a user or as an option notifications on a specific repo.

The only question would be the credentials. There are two scenarios:

Get the user to input `username` and `password` each time they run a command like `getme git`. The console can prompt for the credentials.

Alternatively you could store the credentials in a `user-config.json` file in a `.getme` folder in the User home dir and prompt for the credentials the first time the command is run.

Let me know, I'd be happy to take this.

**Comment by gabrielgodoy** [comment]
@robbiegleeson  If you find that feature useful, you can go ahead :)

**Comment by robbiegleeson** [comment]
@gabrielgodoy you could probably close this issue now
